name: Create Redirect PR

on:
  workflow_dispatch:
    inputs:
      longURL:
        description: 'The original URL'
        required: true
        type: string
      postfix:
        description: 'The custom postfix'
        required: true
        type: string

jobs:
  update-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set safe branch name
        run: |
          POSTFIX="${{ github.event.inputs.postfix }}"
          if [ -z "$POSTFIX" ]; then
            POSTFIX="new-redirect"
          fi
          SAFE_POSTFIX=$(echo "$POSTFIX" | tr -c '[:alnum:]-_' '-')
          echo "BRANCH=add-redirect-$SAFE_POSTFIX" >> $GITHUB_ENV

      - name: Update redirects.json
        run: |
          FILE="r/redirects.json"
          POSTFIX="${{ github.event.inputs.postfix }}"
          URL="${{ github.event.inputs.longURL }}"
          jq --arg k "$POSTFIX" --arg v "$URL" '. + {($k): $v}' $FILE > tmp.json && mv tmp.json $FILE

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH
          git add r/redirects.json
          git commit -m "Add redirect: $POSTFIX -> $URL"
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_PAT }}
          branch: ${{ env.BRANCH }}
          title: "Add redirect ${{ github.event.inputs.postfix }}"
          body: "Automatically created PR to add redirect: ${{ github.event.inputs.postfix }} -> ${{ github.event.inputs.longURL }}"
          base: main
